CREATE OR REPLACE TABLE CUSTOMERS_RAW(
     CUSTOMER_ID NUMBER,
     FIRST_NAME VARCHAR(100),
     LAST_NAME VARCHAR(100),
     EMAIL VARCHAR(200),
     PHONE VARCHAR(20),
     GENDER VARCHAR(20),
     DATE_OF_BIRTH DATE,
     CITY VARCHAR(100),
     STATE VARCHAR(100),
     COUNTRY VARCHAR(100),
     CREATED_DATE TIMESTAMP_NTZ,
     UPDATED_DATE TIMESTAMP_NTZ
);

DESC TABLE CUSTOMERS_RAW;