CREATE OR REPLACE TEMPORARY TABLE TEMP_PAYMENTS AS 
WITH STANDARDIZED_PAYMENTS AS (
  SELECT
    PAYMENT_ID,
    ORDER_ID,
    UPPER(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD,
    UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
    PAYMENT_AMOUNT,
    PAYMENT_DATE
    FROM RAW.PAYMENTS_RAW
),
VALIDATED_PAYMENTS AS (
 SELECT
 *,
 CASE WHEN PAYMENT_ID IS NOT NULL
 AND ORDER_ID IS NOT NULL
 AND PAYMENT_METHOD IS NOT NULL
 AND PAYMENT_METHOD IN ('UPI', 'WALLET', 'CARD', 'NET_BANKING', 'COD')
 AND PAYMENT_STATUS IS NOT NULL
 AND PAYMENT_STATUS IN ('FAILED', 'PENDING', 'SUCCESS', 'REFUNDED')
 AND PAYMENT_AMOUNT IS NOT NULL
 AND PAYMENT_AMOUNT > 0
 AND PAYMENT_DATE IS NOT NULL
 AND PAYMENT_DATE <= CURRENT_TIMESTAMP()
 THEN 'VALID'
 ELSE 'INVALID'
 END AS RECORD_STATUS,
 ARRAY_TO_STRING(
   ARRAY_CONSTRUCT_COMPACT(
      CASE WHEN PAYMENT_ID IS NULL THEN 'MISSING PAYMENT_ID'
      END,
      CASE WHEN ORDER_ID IS NULL THEN 'MISSING ORDER_ID'
      END,
      CASE WHEN PAYMENT_METHOD IS NULL THEN 'MISSING PAYMENT METHOD'
      END,
      CASE WHEN PAYMENT_METHOD NOT IN ('UPI', 'WALLET', 'CARD', 'NET_BANKING', 'COD') THEN 'INVALID PAYMENT METHOD'
      END,
      CASE WHEN PAYMENT_STATUS IS NULL THEN 'MISSING PAYMENT STATUS'
      END,
      CASE WHEN PAYMENT_STATUS NOT IN ('FAILED', 'PENDING', 'SUCCESS', 'REFUNDED') THEN 'INVALID PAYMENT SATUS'
      END,
      CASE WHEN PAYMENT_AMOUNT IS NULL THEN 'MISSING PAYMENT AMOUNT'
      END,
      CASE WHEN PAYMENT_AMOUNT < 0 THEN 'INCORRECT PAYMENT AMOUNT'
      END,
      CASE WHEN PAYMENT_DATE IS NULL THEN 'MISSING PAYMENT DATE'
      END,
      CASE WHEN PAYMENT_DATE > CURRENT_TIMESTAMP() THEN 'INCORRECT PAYMENT DATE'
      END
   ),
   ', '
 ) AS ERROR_REASON
 FROM STANDARDIZED_PAYMENTS
)

SELECT * FROM VALIDATED_PAYMENTS;


INSERT INTO STAGING.ERROR_PAYMENTS(
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    PAYMENT_AMOUNT,
    PAYMENT_DATE,
    ERROR_REASON,
    ERROR_DATE
) 
SELECT
    PAYMENT_ID,
    ORDER_ID,
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    PAYMENT_AMOUNT,
    PAYMENT_DATE,
    ERROR_REASON,
    CURRENT_TIMESTAMP() AS ERROR_DATE
FROM RETAIL_DWH.RAW.TEMP_PAYMENTS
WHERE RECORD_STATUS = 'INVALID';

SELECT 
 (SELECT COUNT(*) FROM RAW.PAYMENTS_RAW) AS RAW_COUNT,
 (SELECT COUNT(*) FROM STAGING.STG_PAYMENTS) AS STG_COUNT,
 (SELECT COUNT(*) FROM STAGING.ERROR_PAYMENTS) AS ERROE_COUNT,
 (SELECT COUNT(*) FROM STAGING.STG_PAYMENTS)
 +
 (SELECT COUNT(*) FROM STAGING.ERROR_PAYMENTS) AS FINAL_COUNT;
 