 CREATE OR REPLACE TABLE STAGING.STG_ORDER_ITEMS(
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(12,2),
    DISCOUNT NUMBER,
    CREATED_DATE TIMESTAMP,
    LOAD_DATE TIMESTAMP
 );