CREATE OR REPLACE TABLE STAGING.ERROR_PRODUCTS(
        PRODUCT_ID NUMBER,
        PRODUCT_NAME VARCHAR(220),
        CATEGORY VARCHAR(100),
        SUB_CATEGORY VARCHAR(100),
        BRAND VARCHAR(100),
        UNIT_PRICE NUMBER(10,2),
        COST_PRICE NUMBER(10,2),
        PRODUCT_STATUS VARCHAR(20),
        CREATED_DATE TIMESTAMP_NTZ,
        UPDATED_DATE TIMESTAMP_NTZ,
        ERROR_REASON VARCHAR(500),
        ERROR_DATE TIMESTAMP
);