CREATE OR REPLACE TABLE STAGING.ERROR_ORDERS(
   ORDER_ID NUMBER,
   CUSTOMER_ID NUMBER,
   ORDER_DATE TIMESTAMP_NTZ,
   ORDER_STATUS VARCHAR(100),
   TOTAL_AMOUNT NUMBER(10,2),
   STORE_ID NUMBER,
   CREATED_DATE TIMESTAMP_NTZ,
   UPDATED_DATE TIMESTAMP_NTZ,
   ERROR_REASON VARCHAR(500),
   ERROR_DATE TIMESTAMP
);