CREATE OR REPLACE TABLE STG_CUSTOMERS(
     CUSTOMER_ID NUMBER,
     FIRST_NAME VARCHAR(100),
     LAST_NAME VARCHAR(100),
     EMAIL VARCHAR(200),
     PHONE VARCHAR(20),
     GENDER VARCHAR(20),
     DATE_OF_BIRTH DATE,
     CITY VARCHAR(100),
     STATE VARCHAR(100),
     COUNTRY VARCHAR(100),
     CUSTOMER_STATUS VARCHAR(20),
     CREATED_DATE TIMESTAMP,
     UPDATED_DATE TIMESTAMP,
     LOAD_DATE TIMESTAMP
);