CREATE OR REPLACE TEMPORARY TABLE TEM_VALIDATED_ORDERS AS 
WITH STANDARDIZED_ORDERS AS 
(
  SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    TOTAL_AMOUNT,
    STORE_ID,
    CREATED_DATE,
    UPDATED_DATE
    FROM RAW.ORDERS_RAW
),
VALIDATED_ORDERS AS 
( 
 SELECT
 *,
 CASE WHEN ORDER_ID IS NOT NULL
 AND CUSTOMER_ID IS NOT NULL
 AND ORDER_DATE <= CREATED_DATE
 AND ORDER_STATUS IN ('DELIVERED', 'CANCELLED', 'SHIPPED', 'CONFIRMED', 'PLACED')
 AND TOTAL_AMOUNT > 0
 AND STORE_ID IS NOT NULL
 AND CREATED_DATE <=  UPDATED_DATE
 AND UPDATED_DATE <= CURRENT_TIMESTAMP()
 THEN 'VALID'
 ELSE 'INVALID'
 END AS RECORD_STATUS,

 ARRAY_TO_STRING(
   ARRAY_CONSTRUCT_COMPACT(
      CASE WHEN ORDER_ID IS NULL THEN 'MISSING ORDER_ID'
      END,
      CASE WHEN CUSTOMER_ID IS NULL THEN 'MISSING CUSTOMER_ID'
      END,
      CASE WHEN ORDER_DATE > CREATED_DATE THEN 'INCORRECT ORDER DATE'
      END,
      CASE WHEN ORDER_STATUS NOT IN ('DELIVERED', 'CANCELLED', 'SHIPPED', 'CONFIRMED', 'PLACED') THEN 'INCORRECT ORDER STATUS'
      END,
      CASE WHEN TOTAL_AMOUNT < 0 THEN 'INCORRECT TOTAL AMOUNT'
      END,
      CASE WHEN STORE_ID IS NULL THEN 'INVALID STORE_ID'
      END,
      CASE WHEN CREATED_DATE > UPDATED_DATE THEN 'INCORRECT CREATED DATE'
      END,
      CASE WHEN UPDATED_DATE > CURRENT_TIMESTAMP() THEN 'INCORRECT UPDATED DATE'
      END
   ),
   ', '
 ) AS ERROR_REASON
 FROM STANDARDIZED_ORDERS
)
SELECT * FROM VALIDATED_ORDERS;

SELECT
RECORD_STATUS,
COUNT(*)
FROM TEM_VALIDATED_ORDERS
GROUP BY RECORD_STATUS;

TRUNCATE TABLE STAGING.ERROR_ORDERS;

INSERT INTO STAGING.ERROR_ORDERS(
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT,
    STORE_ID,
    CREATED_DATE,
    UPDATED_DATE,
    ERROR_REASON,
    ERROR_DATE
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT,
    STORE_ID,
    CREATED_DATE,
    UPDATED_DATE,
    ERROR_REASON,
    CURRENT_TIMESTAMP() AS ERROR_DATE
FROM TEM_VALIDATED_ORDERS
WHERE RECORD_STATUS = 'INVALID';

SELECT
(SELECT COUNT(*) FROM RAW.ORDERS_RAW) AS RAW_COUNT,
(SELECT COUNT(*) FROM STAGING.STG_ORDERS) AS STG_COUNT,
(SELECT COUNT(*) FROM STAGING.ERROR_ORDERS) AS ERR_COUNT,
(SELECT COUNT(*) FROM STAGING.STG_ORDERS)
+
(SELECT COUNT(*) FROM STAGING.ERROR_ORDERS) AS TOTAL_COUNT;
