CREATE OR REPLACE TEMPORARY TABLE TEMP_SHIPMENTS AS 
WITH STANDARDIZED_SHIPMENTS AS (
  SELECT
    SHIPMENT_ID,
    ORDER_ID,
    INITCAP(TRIM(COURIER_NAME)) AS COURIER_NAME,
    UPPER(TRIM(TRACKING_NUMBER)) AS TRACKING_NUMBER,
    UPPER(TRIM(SHIPMENT_STATUS)) AS SHIPMENT_STATUS,
    SHIPPED_DATE,
    DELIVERY_DATE
  FROM RAW.SHIPMENTS_RAW
),
VALIDATED_SHIPMENTS AS (
SELECT
   *,
   CASE WHEN SHIPMENT_ID IS NOT NULL
   AND ORDER_ID IS NOT NULL
   AND COURIER_NAME IS NOT NULL
   AND COURIER_NAME IN ('Xpressbees','Dtdc','Blue Dart','Ecom Express','Delhivery')
   AND TRACKING_NUMBER IS NOT NULL
   AND SHIPMENT_STATUS IS NOT NULL 
   AND SHIPMENT_STATUS IN ('DELIVERED','SHIPPED')
   AND SHIPPED_DATE IS NOT NULL
   AND SHIPPED_DATE <= CURRENT_TIMESTAMP()
   AND 
     (
        (SHIPMENT_STATUS = 'SHIPPED' AND DELIVERY_DATE IS NULL)
        OR
        (SHIPMENT_STATUS = 'DELIVERED' 
         AND DELIVERY_DATE IS NOT NULL
         AND DELIVERY_DATE >= SHIPPED_DATE
         AND DELIVERY_DATE <= CURRENT_TIMESTAMP())) 
    THEN 'VALID'
    ELSE 'INVALID'
    END AS RECORD_STATUS,
    ARRAY_TO_STRING(
       ARRAY_CONSTRUCT_COMPACT(
         CASE WHEN SHIPMENT_ID IS  NULL THEN 'MISSING SHIPMENT_ID'
         END,
         CASE WHEN ORDER_ID IS  NULL THEN 'MISSING ORDER_ID'
         END,
         CASE WHEN COURIER_NAME IS  NULL THEN 'MISSING COURIER NAME'
         END,
         CASE WHEN COURIER_NAME NOT IN ('Xpressbees','Dtdc','Blue Dart','Ecom Express','Delhivery') THEN 'INCORRECT COURIER NAME'
         END,
         CASE WHEN TRACKING_NUMBER IS  NULL THEN 'MISSING TRAKING NUMBER'
         END,
         CASE WHEN SHIPMENT_STATUS IS NULL THEN 'MISSING SHIPMENT STATUS'
         END,
         CASE WHEN SHIPMENT_STATUS NOT IN ('DELIVERED','SHIPPED') THEN 'INCORRECT SHIPMENT STATUS'
         END,
         CASE WHEN SHIPPED_DATE IS NULL THEN 'MISSING SHIPPED DATE'
         END,
         CASE WHEN SHIPPED_DATE > CURRENT_TIMESTAMP() THEN 'FUTURE SHIPPED DATE'
         END,
         CASE WHEN SHIPMENT_STATUS = 'DELIVERED'  AND DELIVERY_DATE IS NULL THEN 'MISSING DELIVARY DATE'
         END,
         CASE WHEN SHIPMENT_STATUS = 'DELIVERED' AND DELIVERY_DATE < SHIPPED_DATE THEN 'DELIVARY DATE BEFORE SHIPPED DATE' 
         END,
         CASE WHEN SHIPMENT_STATUS = 'DELIVERED' AND DELIVERY_DATE > CURRENT_TIMESTAMP() THEN 'FUTURE DELIVARY DATE'
         END,
         CASE WHEN SHIPMENT_STATUS = 'SHIPPED' AND DELIVERY_DATE IS NOT NULL THEN 'UNEXPECTED DELIVARY DATE'
         END
       ),
       ', '
    ) AS ERROR_REASON
    FROM STANDARDIZED_SHIPMENTS
) 
SELECT * FROM VALIDATED_SHIPMENTS;


INSERT INTO STAGING.STG_SHIPMENTS(
    SHIPMENT_ID,
    ORDER_ID,
    COURIER_NAME,
    TRACKING_NUMBER,
    SHIPMENT_STATUS,
    SHIPPED_DATE,
    DELIVERY_DATE,
    LOAD_DATE
)
SELECT
    SHIPMENT_ID,
    ORDER_ID,
    COURIER_NAME,
    TRACKING_NUMBER,
    SHIPMENT_STATUS,
    SHIPPED_DATE,
    DELIVERY_DATE,
    CURRENT_TIMESTAMP() AS LOAD_DATE
FROM RETAIL_DWH.RAW.TEMP_SHIPMENTS
WHERE RECORD_STATUS = 'VALID';

SELECT COUNT(*) FROM STAGING.STG_SHIPMENTS;
