INSERT INTO STAGING.ERROR_CUSTOMERS(
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_STATUS,
    CREATED_DATE,
    UPDATED_DATE,
    ERROR_REASON,
    ERROR_DATE
)
WITH STANDARDIZED_CUSTOMERS AS 
(
  SELECT
  CUSTOMER_ID,
  INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME, 
  INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
  LOWER(TRIM(EMAIL)) AS EMAIL,
  TRIM(PHONE) AS PHONE,
  INITCAP(TRIM(GENDER)) AS GENDER,
  DATE_OF_BIRTH,
  INITCAP(TRIM(CITY)) AS CITY,
  INITCAP(TRIM(STATE)) AS STATE,
  INITCAP(TRIM(COUNTRY)) AS COUNTRY,
  UPPER(TRIM(CUSTOMER_STATUS)) AS CUSTOMER_STATUS,
  CREATED_DATE,
  UPDATED_DATE
FROM RAW.CUSTOMERS_RAW 
),
VALIDATED_CUSTOMERS AS
(
  SELECT
  *,
  CASE 
      WHEN REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')   
      AND 
      REGEXP_LIKE(PHONE,'^[0-9]{10}$')
      AND 
      DATE_OF_BIRTH <= CURRENT_DATE()
      THEN 'VALID'
      ELSE 'INVALID'
  END AS RECORD_STATUS,
  ARRAY_TO_STRING(

 ARRAY_CONSTRUCT_COMPACT(
      CASE WHEN EMAIL IS NULL THEN 'MISSING EMAIL'
           WHEN NOT REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 'INVALID EMAIL'
      END,
      CASE WHEN PHONE IS NULL THEN 'MISSING PHONE'
           WHEN NOT REGEXP_LIKE(PHONE,'^[0-9]{10}$') THEN 'INVALID PHONE'
     END,
     CASE WHEN DATE_OF_BIRTH IS NULL THEN 'MISSING DOB'
          WHEN DATE_OF_BIRTH > CURRENT_DATE() THEN 'FUTURE DOB'
    END
 ),
 ', '
  ) AS ERROR_REASON
FROM STANDARDIZED_CUSTOMERS
)

SELECT 
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_STATUS,
    CREATED_DATE,
    UPDATED_DATE,
    ERROR_REASON,
    CURRENT_TIMESTAMP() AS ERROR_DATE
FROM VALIDATED_CUSTOMERS
WHERE RECORD_STATUS = 'INVALID';

SELECT
COUNT(*) FROM STAGING.ERROR_CUSTOMERS;

SELECT 
  (SELECT COUNT(*) FROM RAW.CUSTOMERS_RAW) AS RAW_COUNT,
  (SELECT COUNT(*) FROM STAGING.STG_CUSTOMERS) AS VALID_COUNT,
  (SELECT COUNT(*) FROM STAGING.ERROR_CUSTOMERS) AS ERR0R_COUNT,
  (SELECT COUNT(*) FROM STAGING.STG_CUSTOMERS)
  +
  (SELECT COUNT(*) FROM STAGING.ERROR_CUSTOMERS) AS FINAL_STG;

