INSERT INTO STAGING.ERROR_PRODUCTS(
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  SUB_CATEGORY,
  BRAND,
  UNIT_PRICE,
  COST_PRICE,
  PRODUCT_STATUS,
  CREATED_DATE,
  UPDATED_DATE,
  ERROR_REASON,
  ERROR_DATE
)
WITH STANDARDIZED_PRODUCTS AS (
  SELECT
     PRODUCT_ID,
     INITCAP(TRIM(PRODUCT_NAME)) AS PRODUCT_NAME,
     INITCAP(TRIM(CATEGORY)) AS CATEGORY,
     INITCAP(TRIM(SUB_CATEGORY)) AS SUB_CATEGORY,
     INITCAP(TRIM(BRAND)) AS BRAND,
     UNIT_PRICE,
     COST_PRICE,
     UPPER(TRIM(PRODUCT_STATUS)) AS PRODUCT_STATUS,
     CREATED_DATE,
     UPDATED_DATE
     FROM RAW.PRODUCTS_RAW
),
VALIDATED_PRODUCTS AS 
(
 SELECT
 *,
 CASE WHEN PRODUCT_ID IS NOT NULL
 AND PRODUCT_NAME IS NOT NULL
 AND CATEGORY IS NOT NULL
 AND SUB_CATEGORY IS NOT NULL
 AND BRAND IS NOT NULL
 AND UNIT_PRICE > 0
 AND COST_PRICE > 0
 AND COST_PRICE <= UNIT_PRICE
 AND PRODUCT_STATUS IN ('ACTIVE', 'INACTIVE','DISCONTINUED')
 AND CREATED_DATE < CURRENT_TIMESTAMP()
 AND UPDATED_DATE >= CREATED_DATE
 THEN 'VALID'
 ELSE 'INVALID'
 END AS RECORD_STATUS,

 ARRAY_TO_STRING(
   ARRAY_CONSTRUCT_COMPACT(
      CASE WHEN PRODUCT_ID IS NULL THEN 'MISSING PRODUCT_ID'
      END,
      CASE WHEN PRODUCT_NAME IS NULL THEN 'MISSING PRODUCT NAME'
      END,
      CASE WHEN CATEGORY IS NULL THEN 'MISSING CATEGORY'
      END,
      CASE WHEN SUB_CATEGORY IS NULL THEN 'MISSING SUB CATEGORY'
      END,
      CASE WHEN BRAND IS NULL THEN 'MISSING BRAND'
      END,
      CASE WHEN UNIT_PRICE <= 0 THEN 'INVALID UNIT PRICE'
      END,
      CASE WHEN COST_PRICE <= 0 THEN 'INVALID COST PRICE'
      END, 
      CASE WHEN COST_PRICE > UNIT_PRICE THEN 'INCORRECT COST PRICE'
      END,
      CASE WHEN PRODUCT_STATUS NOT IN ('ACTIVE', 'INACTIVE','DISCONTINUED') THEN 'INCORRECT PRODUCT STATUS'
      END,
      CASE WHEN CREATED_DATE > CURRENT_TIMESTAMP() THEN 'INCORRECT CREATED DATE'
      END,
      CASE WHEN UPDATED_DATE < CREATED_DATE THEN 'INCORRECT UPDATED DATE'
      END
   ),
   ', '
 ) AS ERROR_REASON
 FROM STANDARDIZED_PRODUCTS 
)

SELECT
  PRODUCT_ID,
  PRODUCT_NAME,
  CATEGORY,
  SUB_CATEGORY,
  BRAND,
  UNIT_PRICE,
  COST_PRICE,
  PRODUCT_STATUS,
  CREATED_DATE,
  UPDATED_DATE,
  ERROR_REASON,
  CURRENT_TIMESTAMP() AS ERROR_DATE
FROM VALIDATED_PRODUCTS
WHERE RECORD_STATUS = 'INVALID';

SELECT
    (SELECT COUNT(*) FROM RAW.PRODUCTS_RAW) AS RAW_COUNT,
    (SELECT COUNT(*) FROM STAGING.STG_PRODUCTS) AS VALID_STG_COUNT,
    (SELECT COUNT(*) FROM STAGING.ERROR_PRODUCTS) AS INVALID_STG_COUNT,
    (SELECT COUNT(*) FROM STAGING.STG_PRODUCTS)
    +
    (SELECT COUNT(*) FROM STAGING.ERROR_PRODUCTS) AS TTL_STG_COUNT;
