CREATE OR REPLACE TABLE ORDER_ITEMS_RAW(
       ORDER_ITEM_ID NUMBER,
       ORDER_ID NUMBER,
       PRODUCT_ID NUMBER,
       QUANTITY NUMBER,
       UNIT_PRICE NUMBER(10,2),
       DISCOUNT NUMBER(10,2),
       CREATED_DATE TIMESTAMP_NTZ
);

DESC TABLE ORDER_ITEMS_RAW;