create or REPLACE TABLE ORDERS_RAW(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE TIMESTAMP_NTZ,
    ORDER_STATUS VARCHAR(50),
    TOTAL_AMOUNT NUMBER(12,2),
    STORE_ID NUMBER,
    CREATED_DATE TIMESTAMP_NTZ,
    UPDATED_DATE TIMESTAMP_NTZ
);

DESC TABLE ORDERS_RAW;