CREATE OR REPLACE TABLE PAYMENTS_RAW(
       PAYMENT_ID NUMBER,
       ORDER_ID NUMBER,
       PAYMENT_METHOD VARCHAR(50),
       PAYMENT_STATUS VARCHAR(30),
       PAYMENT_AMOUNT NUMBER(12,2),
       PAYMENT_DATE TIMESTAMP_NTZ
);

DESC TABLE PAYMENTS_RAW;