CREATE OR REPLACE TABLE SHIPMENTS_RAW(
       SHIPMENT_ID NUMBER,
       ORDER_ID NUMBER,
       COURIER_NAME VARCHAR(100),
       TRACKING_NUMBER VARCHAR(100),
       SHIPMENT_STATUS VARCHAR(50),
       SHIPPED_DATE TIMESTAMP_NTZ,
       DELIVERY_DATE TIMESTAMP_NTZ
);

DESC TABLE SHIPMENTS_RAW;