
INSERT INTO DW.FACT_PAYMENTS(

    PAYMENT_ID,
    ORDER_ID ,
    CUSTOMER_KEY,
    PAYMENT_DATE_KEY,
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    PAYMENT_AMOUNT,
    CREATED_AT ,
    UPDATED_AT 
)

SELECT

    P.PAYMENT_ID,
    P.ORDER_ID ,
    COALESCE(CUSTOMER_KEY,0),
    DD.DATE_KEY,
    P.PAYMENT_METHOD,
    P.PAYMENT_STATUS,
    P.PAYMENT_AMOUNT,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM ODS.ODS_PAYMENTS AS P
INNER JOIN ODS.ODS_ORDERS AS O
ON P.ORDER_ID = O.ORDER_ID
LEFT JOIN DW.DIM_CUSTOMER AS DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID
LEFT JOIN DW.DIM_DATE AS DD
ON CAST(P.PAYMENT_DATE AS DATE) = DD.FULL_DATE;

SELECT COUNT(*) FROM DW.FACT_PAYMENTS;

SELECT COUNT(*) FROM DW.FACT_PAYMENTS
WHERE CUSTOMER_KEY = 0;

SELECT COUNT(*) FROM DW.FACT_PAYMENTS
WHERE PAYMENT_DATE_KEY IS NULL;

SELECT SUM(PAYMENT_AMOUNT) FROM DW.FACT_PAYMENTS;

SELECT
PAYMENT_STATUS,
COUNT(*) AS CNT
FROM DW.FACT_PAYMENTS
GROUP BY PAYMENT_STATUS
ORDER BY COUNT(*) DESC;