INSERT INTO DW.DIM_PRODUCT(
    PRODUCT_KEY,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    PRODUCT_STATUS,
    CREATED_AT,
    UPDATED_AT
)
VALUES(
    0,
    -1,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);

SELECT * FROM DW.DIM_PRODUCT;
