DESC TABLE DW.DIM_DATE;

INSERT INTO DW.DIM_DATE(
DATE_KEY,
FULL_DATE,
DAY_NUMBER,
DAY_NAME,
WEEK_NUMBER,
MONTH_NUMBER,
MONTH_NAME,
QUARTER_NUMBER,
QUARTER_NAME,
YEAR_NUMBER,
IS_WEEKEND
)
SELECT
   TO_NUMBER(TO_CHAR(FULL_DATE,'YYYYMMDD')) AS DATE_KEY,
   FULL_DATE,
   DAY(FULL_DATE) AS DAY_NUMBER,
   DAYNAME(FULL_DATE) AS DAY_NAME,
   WEEKOFYEAR(FULL_DATE) AS WEEK_NUMBER,
   MONTH(FULL_DATE) AS MONTH_NUMBER,
   MONTHNAME(FULL_DATE) AS MONTH_NAME,
   QUARTER(FULL_DATE) AS QUARTER_NUMBER,
   'Q' || QUARTER(FULL_DATE) AS QUARTER_NAME,
   YEAR(FULL_DATE) AS YEAR_NUMBER,
   DAYOFWEEKISO(FULL_DATE) IN (6,7) AS IS_WEEKEND
   FROM (
         SELECT
            DATEADD(DAY,SEQ4(),DATE '2024-01-01') AS FULL_DATE
            FROM TABLE(GENERATOR(ROWCOUNT => 1000))
   )
   WHERE FULL_DATE <= DATE '2026-07-10';

   SELECT COUNT(*) FROM DW.DIM_DATE;
   
   SELECT 
   DATE_KEY,
   COUNT(*) AS CNT
   FROM DW.DIM_DATE
   GROUP BY DATE_KEY
   HAVING COUNT(*) > 1 

   SELECT 
   FULL_DATE,
   COUNT(*) AS CNT 
   FROM DW.DIM_DATE
   GROUP BY FULL_DATE
   HAVING COUNT(*) > 1

   SELECT 
   MIN(FULL_DATE) AS MIN_DATE,
   MAX(FULL_DATE) AS MAX_DATE
   FROM DW.DIM_DATE

   SELECT
   IS_WEEKEND,
   COUNT(*) AS DAYS
   FROM DW.DIM_DATE
   GROUP BY IS_WEEKEND
    
