INSERT INTO DW.FACT_SALES(

    ORDER_ID,
    ORDER_ITEM_ID,
    CUSTOMER_KEY,
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    GROSS_AMOUNT,
    NET_SALES,
    TOTAL_COST,
    PROFIT,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    OI.ORDER_ID,
    OI.ORDER_ITEM_ID,
    COALESCE(DC.CUSTOMER_KEY,0) AS CUSTOMER_KEY,
    COALESCE(DP.PRODUCT_KEY,0) AS PRODUCT_KEY,
    DD.DATE_KEY,
    OI.QUANTITY,
    OI.UNIT_PRICE,
    OI.DISCOUNT,
    (OI.QUANTITY * OI.UNIT_PRICE) AS GROSS_AMOUNT,
    ((OI.QUANTITY * OI.UNIT_PRICE) - OI.DISCOUNT) AS NET_SALES,
    (OI.QUANTITY * COALESCE(P.COST_PRICE,0)) AS TOTAL_COST,
    (((OI.QUANTITY * OI.UNIT_PRICE) - OI.DISCOUNT) - (OI.QUANTITY * P.COST_PRICE)) AS PROFIT,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM ODS.ODS_ORDER_ITEMS AS OI
INNER JOIN ODS.ODS_ORDERS AS O
ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN ODS.ODS_PRODUCTS AS P
ON OI.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN DW.DIM_CUSTOMER AS DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID
LEFT JOIN DW.DIM_PRODUCT AS DP
ON OI.PRODUCT_ID = DP.PRODUCT_ID
LEFT JOIN DW.DIM_DATE AS DD
ON CAST(O.ORDER_DATE AS DATE) = DD.FULL_DATE;

SELECT 
COUNT(*) 
FROM ODS.ODS_ORDER_ITEMS AS OI
INNER JOIN ODS.ODS_ORDERS AS O
ON OI.ORDER_ID = O.ORDER_ID

SELECT 
COUNT(*) 
FROM ODS.ODS_ORDER_ITEMS AS OI
INNER JOIN ODS.ODS_ORDERS AS O
ON OI.ORDER_ID = O.ORDER_ID
INNER JOIN ODS.ODS_PRODUCTS AS P
ON OI.PRODUCT_ID = P.PRODUCT_ID

SELECT 
COUNT(*)
FROM ODS.ODS_ORDER_ITEMS AS OI 
LEFT JOIN ODS.ODS_ORDERS AS O
ON OI.ORDER_ID = O.ORDER_ID
WHERE O.ORDER_ID IS NULL;

SELECT COUNT(*) FROM DW.FACT_SALES;

SELECT COUNT(*) FROM DW.FACT_SALES WHERE CUSTOMER_KEY = 0;

SELECT COUNT(*) FROM DW.FACT_SALES WHERE PRODUCT_KEY = 0;

SELECT 
SUM(GROSS_AMOUNT) AS GROSS_SALE,
SUM(NET_SALES) AS NET_SALE,
SUM(TOTAL_COST) AS TOTAL_COST,
SUM(PROFIT) AS PROFIT
FROM DW.FACT_SALES;

SELECT
COUNT(*)
FROM DW.FACT_SALES
WHERE PROFIT < 0;

