INSERT INTO DW.FACT_SHIPMENTS(

    SHIPMENT_ID ,
    ORDER_ID ,
    CUSTOMER_KEY,
    SHIPPED_DATE_KEY,
    DELIVERY_DATE_KEY,
    COURIER_NAME,
    TRACKING_NUMBER ,
    SHIPMENT_STATUS ,
    CREATED_AT ,
    UPDATED_AT 
)

SELECT
    S.SHIPMENT_ID ,
    S.ORDER_ID ,
    COALESCE(DC.CUSTOMER_KEY,0) AS CUSTOMER_KEY,
    SD.DATE_KEY AS SHIPPED_DATE_KEY,
    DD.DATE_KEY AS DELIVERY_DATE_KEY,
    S.COURIER_NAME,
    S.TRACKING_NUMBER ,
    S.SHIPMENT_STATUS ,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM ODS.ODS_SHIPMENTS AS S
INNER JOIN ODS.ODS_ORDERS AS O
ON S.ORDER_ID = O.ORDER_ID
LEFT JOIN DIM_CUSTOMER AS DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID
LEFT JOIN DW.DIM_DATE AS SD
ON CAST(S.SHIPPED_DATE AS DATE) = SD.FULL_DATE
LEFT JOIN DW.DIM_DATE AS DD
ON CAST(S.DELIVERY_DATE AS DATE) = DD.FULL_DATE;

SELECT * FROM DW.FACT_SHIPMENTS LIMIT 100;

SELECT 
COUNT(*)
FROM DW.FACT_SHIPMENTS
WHERE CUSTOMER_KEY = 0;

SELECT 
COUNT(*)
FROM DW.FACT_SHIPMENTS
WHERE SHIPPED_DATE_KEY IS NULL;

SELECT 
COUNT(*)
FROM DW.FACT_SHIPMENTS
WHERE DELIVERY_DATE_KEY IS NULL;

SELECT 
SHIPMENT_ID,
COUNT(*)
FROM DW.FACT_SHIPMENTS
GROUP BY SHIPMENT_ID
HAVING COUNT(*) > 1;

SELECT
SHIPMENT_STATUS,
COUNT(*)
FROM DW.FACT_SHIPMENTS
GROUP BY SHIPMENT_STATUS;