SELECT
MAX(DATEDIFF(YEAR, DATE_OF_BIRTH, CURRENT_TIMESTAMP())) AS MAX_A,
MIN(DATEDIFF(YEAR, DATE_OF_BIRTH, CURRENT_TIMESTAMP())) AS MIN_A
FROM ODS.ODS_CUSTOMERS;

INSERT INTO DW.DIM_CUSTOMER(
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DATE_OF_BIRTH,
    AGE_GROUP,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_STATUS,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DATE_OF_BIRTH,
    CASE WHEN DATEDIFF(YEAR,DATE_OF_BIRTH,CURRENT_DATE()) BETWEEN 22 AND 25 THEN '22-25'
         WHEN DATEDIFF(YEAR,DATE_OF_BIRTH,CURRENT_DATE()) BETWEEN 26 AND 30 THEN '26-30'
         WHEN DATEDIFF(YEAR,DATE_OF_BIRTH,CURRENT_DATE()) BETWEEN 31 AND 35 THEN '31-35'
         WHEN DATEDIFF(YEAR,DATE_OF_BIRTH,CURRENT_DATE()) BETWEEN 36 AND 41 THEN '36-41'
         ELSE 'UNKNOWN'
    END AS AGE_GROUP,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_STATUS,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM ODS.ODS_CUSTOMERS;

SELECT COUNT(*) FROM DW.DIM_CUSTOMER 
WHERE CUSTOMER_KEY <> 0;

SELECT
CUSTOMER_ID,
COUNT(*) AS DIS
FROM DW.DIM_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT
AGE_GROUP,
COUNT(*) AS CNT
FROM DW.DIM_CUSTOMER
GROUP BY AGE_GROUP
ORDER BY COUNT(*) DESC;

SELECT COUNT(*) FROM ODS.ODS_CUSTOMERS;

SELECT COUNT(DISTINCT CUSTOMER_ID) FROM DW.DIM_CUSTOMER;

SELECT
  (SELECT COUNT(*) FROM STAGING.STG_CUSTOMERS) AS STG_CNT,
  (SELECT COUNT(*) FROM ODS.ODS_CUSTOMERS) AS ODS_CNT,
  (SELECT COUNT(*) FROM DW.DIM_CUSTOMER WHERE CUSTOMER_KEY <> 0) AS DW_VALID_VNT,
  (SELECT COUNT(*) FROM DW.DIM_CUSTOMER) AS TTL_DW_CNT,
  (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM DW.DIM_CUSTOMER) AS DW_DIST_CNT;
