 CREATE OR REPLACE TABLE STAGING.ERROR_ORDER_ITEMS(
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(12,2),
    DISCOUNT NUMBER,
    CREATED_DATE TIMESTAMP,
    ERROR_REASON VARCHAR(500),
    ERROR_DATE TIMESTAMP
 );