CREATE OR REPLACE TABLE STAGING.ERROR_SHIPMENTS(
    SHIPMENT_ID NUMBER,
    ORDER_ID NUMBER,
    COURIER_NAME VARCHAR(200),
    TRACKING_NUMBER VARCHAR(100),
    SHIPMENT_STATUS VARCHAR(50),
    SHIPPED_DATE TIMESTAMP,
    DELIVERY_DATE TIMESTAMP,
    ERROR_REASON VARCHAR(500),
    ERROR_DATE TIMESTAMP
);