MERGE INTO ODS.ODS_PRODUCTS AS T
USING RETAIL_DWH.RAW.TEMP_PRODUCTS_INCREMENTAL AS S
ON T.PRODUCT_ID = S.PRODUCT_ID
WHEN MATCHED THEN
UPDATE SET

    T.PRODUCT_NAME = S.PRODUCT_NAME,
    T.CATEGORY = S.CATEGORY,
    T.SUB_CATEGORY = S.SUB_CATEGORY,
    T.BRAND = S.BRAND,
    T.UNIT_PRICE = S.UNIT_PRICE,
    T.COST_PRICE = S.COST_PRICE,
    T.PRODUCT_STATUS = S.PRODUCT_STATUS,
    T.CREATED_DATE = S.CREATED_DATE,
    T.UPDATED_DATE = S.UPDATED_DATE,
    T.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
INSERT 
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    UNIT_PRICE,
    COST_PRICE,
    PRODUCT_STATUS,
    CREATED_DATE,
    UPDATED_DATE,
    CREATED_AT,
    UPDATED_AT
)
VALUES
(
    S.PRODUCT_ID,
    S.PRODUCT_NAME,
    S.CATEGORY,
    S.SUB_CATEGORY,
    S.BRAND,
    S.UNIT_PRICE,
    S.COST_PRICE,
    S.PRODUCT_STATUS,
    CREATED_DATE,
    UPDATED_DATE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);
