CREATE OR REPLACE TEMPORARY TABLE TEMP_PRODUCTS_INCREMENTAL LIKE STAGING.STG_PRODUCTS;
SELECT * FROM RETAIL_DWH.RAW.TEMP_PRODUCTS_INCREMENTAL;
DESC TABLE STAGING.STG_PRODUCTS;

INSERT INTO TEMP_PRODUCTS_INCREMENTAL
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    UNIT_PRICE + 100 AS UNIT_PRICE,
    COST_PRICE,
    'INACTIVE' AS PRODUCT_STATUS,
    CREATED_DATE,
    CURRENT_TIMESTAMP() AS UPDATED_DATE,
    LOAD_DATE
FROM STAGING.STG_PRODUCTS
WHERE PRODUCT_ID IN (SELECT PRODUCT_ID
                      FROM STAGING.STG_PRODUCTS
                      ORDER BY PRODUCT_ID
                      LIMIT 2);

SELECT * FROM TEMP_PRODUCTS_INCREMENTAL;

INSERT INTO TEMP_PRODUCTS_INCREMENTAL
SELECT
    (SELECT MAX(PRODUCT_ID)
    FROM STAGING.STG_PRODUCTS)
    + ROW_NUMBER() OVER 
    (ORDER BY PRODUCT_ID)
     AS
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    UNIT_PRICE,
    COST_PRICE,
    PRODUCT_STATUS,
    CURRENT_TIMESTAMP() AS CREATED_DATE,
    CURRENT_TIMESTAMP() AS UPDATED_DATE,
    LOAD_DATE
FROM STAGING.STG_PRODUCTS
ORDER BY PRODUCT_ID
LIMIT 2;
