/*
TEST DATA FOR INCREMENTAL LOADING 
1.UPDATED EXESTING RECORDS AND CREATED NEW RECORDS
2.USED MERGE INTO TO TEST INCREMENTAL LOAD IN ODS LAYER
*/

CREATE OR REPLACE TEMPORARY TABLE TEMP_CUSTOMERS_INCREMENTAL AS 
SELECT * FROM STAGING.STG_CUSTOMERS
where 1=0;


SELECT COUNT(*) FROM TEMP_CUSTOMERS_INCREMENTAL;

DESC TABLE TEMP_CUSTOMERS_INCREMENTAL;

SELECT 
  MIN(CUSTOMER_ID),
  MAX(CUSTOMER_ID)
FROM STAGING.STG_CUSTOMERS;

INSERT INTO RETAIL_DWH.RAW.TEMP_CUSTOMERS_INCREMENTAL

SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    STATE,
    COUNTRY,
    'INACTIVE' AS CUSTOMER_STATUS,
    CREATED_DATE,
    CURRENT_TIMESTAMP() AS UPDATED_DATE,
    LOAD_DATE
FROM STAGING.STG_CUSTOMERS
WHERE CUSTOMER_ID IN (100002,100003,100004);


SELECT * FROM RETAIL_DWH.RAW.TEMP_CUSTOMERS_INCREMENTAL; 

show parameters like 'timezone' in session;
ALTER SESSION SET TIMEZONE = 'Asia/Kolkata';
SELECT CURRENT_TIMESTAMP();

INSERT INTO RETAIL_DWH.RAW.TEMP_CUSTOMERS_INCREMENTAL
SELECT
    CUSTOMER_ID + 5000,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_STATUS,
    CURRENT_TIMESTAMP() AS CREATED_DATE,
    CURRENT_TIMESTAMP() AS UPDATED_DATE,
    CURRENT_TIMESTAMP() AS LOAD_DATE
FROM STAGING.STG_CUSTOMERS
WHERE CUSTOMER_ID IN (100002,100003);

SELECT 
CUSTOMER_ID,
CUSTOMER_STATUS,
CREATED_DATE
UPDATED_DATE,
LOAD_DATE
FROM RETAIL_DWH.RAW.TEMP_CUSTOMERS_INCREMENTAL
ORDER BY CUSTOMER_ID;

