CREATE OR REPLACE TABLE  STAGING.STG_PRODUCTS(
        PRODUCT_ID NUMBER,
        PRODUCT_NAME VARCHAR(220),
        CATEGORY VARCHAR(100),
        SUB_CATEGORY VARCHAR(100),
        BRAND VARCHAR(100),
        UNIT_PRICE NUMBER(10,2),
        COST_PRICE NUMBER(10,2),
        PRODUCT_STATUS VARCHAR(20),
        CREATED_DATE TIMESTAMP_NTZ,
        UPDATED_DATE TIMESTAMP_NTZ,
        LOAD_DATE TIMESTAMP_NTZ
);

SELECT * FROM STAGING.STG_PRODUCTS;

DESC TABLE STAGING.STG_PRODUCTS;
