CREATE OR REPLACE TABLE STAGING.ERROR_PAYMENTS(
    PAYMENT_ID NUMBER,
    ORDER_ID NUMBER,
    PAYMENT_METHOD VARCHAR(100),
    PAYMENT_STATUS VARCHAR(100),
    PAYMENT_AMOUNT NUMBER,
    PAYMENT_DATE TIMESTAMP,
    ERROR_REASON VARCHAR(500),
    ERROR_DATE TIMESTAMP
);