INSERT INTO DW.DIM_PRODUCT(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    PRODUCT_STATUS,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    PRODUCT_STATUS,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM ODS.ODS_PRODUCTS;

SELECT
  (SELECT COUNT(*) FROM STAGING.STG_PRODUCTS) AS STG_CNT,
  (SELECT COUNT(*) FROM ODS.ODS_PRODUCTS) AS ODS_COUNT,
  (SELECT COUNT(*) FROM DW.DIM_PRODUCT) AS DIM_TTL_COUNT,
  (SELECT COUNT(*) FROM DW.DIM_PRODUCT WHERE PRODUCT_KEY <> 0) AS VALID_DW_CNT

SELECT
PRODUCT_ID,
COUNT(*) AS CNT
FROM DW.DIM_PRODUCT
GROUP BY PRODUCT_ID
HAVING COUNT(*)>1;

SELECT
COUNT(*) AS CNT
FROM DW.DIM_PRODUCT
WHERE PRODUCT_KEY IS NULL;

SELECT
CATEGORY,
COUNT(*) AS CNT
FROM DW.DIM_PRODUCT
GROUP BY CATEGORY
ORDER BY COUNT(*) DESC;
