CREATE OR REPLACE TEMPORARY TABLE TEMP_VALIDATED_ORDER_ITEMS AS 
WITH VALIDATED_ORDER_ITEMS AS (
SELECT
   *,
   CASE WHEN ORDER_ITEM_ID IS NOT NULL
   AND ORDER_ID IS NOT NULL
   AND PRODUCT_ID IS NOT NULL
   AND QUANTITY > 0
   AND UNIT_PRICE > 0
   AND DISCOUNT >= 0
   AND DISCOUNT <= QUANTITY*UNIT_PRICE
   AND CREATED_DATE IS NOT NULL
   AND CREATED_DATE <= CURRENT_TIMESTAMP()
   THEN 'VALID'
   ELSE 'INVALID'
 END AS RECORD_STATUS,
  ARRAY_TO_STRING(
      ARRAY_CONSTRUCT_COMPACT(
           CASE WHEN ORDER_ITEM_ID IS NULL THEN 'MISSING ORDER ITEM_ID'
           END,
           CASE WHEN ORDER_ID IS NULL THEN 'MISSING ORDER_ID'
           END,
           CASE WHEN PRODUCT_ID IS NULL THEN 'MISSING PRODUCT_ID'
           END,
           CASE WHEN QUANTITY <= 0 THEN 'INCORRECT QUANTITY'
           END,
           CASE WHEN UNIT_PRICE <= 0 THEN 'INCORRECT UNIT PRICE'
           END,
           CASE WHEN DISCOUNT < 0 THEN 'INCORRECT DISCOUNT'
           END,
           CASE WHEN DISCOUNT > QUANTITY*UNIT_PRICE THEN 'INVALID DISCOUNT'
           END,
           CASE WHEN CREATED_DATE IS NULL THEN 'MISSING DATE'
           END,
           CASE WHEN CREATED_DATE > CURRENT_TIMESTAMP() THEN 'INCORRECT CREATED DATE'
           END
      ),
      ', '
     )
  AS ERROR_REASON
  FROM RAW.ORDER_ITEMS_RAW
 )
 SELECT * FROM VALIDATED_ORDER_ITEMS;

INSERT INTO STAGING.STG_ORDER_ITEMS(
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    CREATED_DATE, 
    LOAD_DATE
)
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    CREATED_DATE,
    CURRENT_TIMESTAMP() AS LOAD_DATE
FROM TEMP_VALIDATED_ORDER_ITEMS
WHERE RECORD_STATUS = 'VALID';

SELECT COUNT(*) FROM STAGING.STG_ORDER_ITEMS;