INSERT INTO STAGING.STG_CUSTOMERS(
       CUSTOMER_ID,
       FIRST_NAME,
       LAST_NAME,
       EMAIL,
       PHONE,
       GENDER,
       DATE_OF_BIRTH,
       CITY,
       STATE,
       COUNTRY,
       CUSTOMER_STATUS,
       CREATED_DATE,
       UPDATED_DATE,
       LOAD_DATE
)

WITH STANDARDIZED_CUSTOMERS AS 
(
  SELECT
  CUSTOMER_ID,
  INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME, 
  INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
  LOWER(TRIM(EMAIL)) AS EMAIL,
  TRIM(PHONE) AS PHONE,
  INITCAP(TRIM(GENDER)) AS GENDER,
  DATE_OF_BIRTH,
  INITCAP(TRIM(CITY)) AS CITY,
  INITCAP(TRIM(STATE)) AS STATE,
  INITCAP(TRIM(COUNTRY)) AS COUNTRY,
  UPPER(TRIM(CUSTOMER_STATUS)) AS CUSTOMER_STATUS,
  CREATED_DATE,
  UPDATED_DATE
FROM RAW.CUSTOMERS_RAW 
),

VALIDATED_CUSTOMERS AS
(
  SELECT
  *,
  CASE 
      WHEN REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
      AND
      REGEXP_LIKE(PHONE,'^[0-9]{10}$')
      AND 
      DATE_OF_BIRTH <= CURRENT_DATE()
      THEN 'VALID'
      ELSE 'INVALID'
  END AS RECORD_STATUS
FROM STANDARDIZED_CUSTOMERS
)

SELECT
       CUSTOMER_ID,
       FIRST_NAME,
       LAST_NAME,
       EMAIL,
       PHONE,
       GENDER,
       DATE_OF_BIRTH,
       CITY,
       STATE,
       COUNTRY,
       CUSTOMER_STATUS,
       CREATED_DATE,
       UPDATED_DATE,
       CURRENT_TIMESTAMP() AS LOAD_DATE
FROM VALIDATED_CUSTOMERS
WHERE RECORD_STATUS = 'VALID';

SELECT * FROM STAGING.STG_CUSTOMERS LIMIT 28;

SELECT COUNT(*)
FROM STAGING.STG_CUSTOMERS
WHERE NOT REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
OR
NOT REGEXP_LIKE(PHONE,'^[0-9]{10}$')
OR
DATE_OF_BIRTH > CURRENT_DATE();